### ISSUE TITLE
TML exports failing after thoughtspot version upgrade from 7.1.1 to 8.8.1.sw.cu1 

### ISSUE THREAD

**Issue by venkataswetha1997** [thoughtspot/thoughtspot_tml#11]
I'm using TSRESTAPIV1 and everything was working fine until the upgrade is done. Now the ThouughtSpot was updated to 8.8.1.sw.cu1 . May I please know if I need to do any additional updates in order to export the TML's for answers, worksheet, tables and liveboards. I'm currently using these scripts. 

1. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/examples/tml_and_sdlc/tml_yaml_intro.py
2. https://github.com/thoughtspot/thoughtspot_rest_api_v1_python/blob/main/src/thoughtspot_rest_api_v1/tsrestapiv1.py
3. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/endpoint_method_classes.py
4. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/thoughtspot.py

**Comment by boonhapus** [comment]
7.1.1 is a very old ThoughtSpot version and APIs have changed significantly since then. For API access consumption we should use **[TS REST API V1](https://github.com/thoughtspot/thoughtspot_rest_api_v1_python)**. This should have a working implementation of the APIs even for TS 8.8.1 .

For interaction with **[ThoughtSpot TML objects](https://github.com/thoughtspot/thoughtspot_tml)**, use this library.

@venkataswetha1997 If you still find issues with the restv1 api project, can you open this issue in that repository instead? This repository is for `thoughtspot_tml` only.

**Comment by venkataswetha1997** [comment]
Hi @boonhapus , I'm using YAMLTML class in my script. My previous version was 1.1.1 and I saw issues with that. Then you have suggested to upgrade my thoughtspot-tml after the changes were made and that helped me resolve the issues. But now when I'm upgrading the thoughtspot-tml that's being directed to 2.0.4 and tml export is failing. May I please know if there is way I can revert back to the version that's fully updated but not to 2.0.4(python -c "import pkg_resources; print(pkg_resources.get_distribution('thoughtspot_tml').version)"). I think the issue is with the thoughtspot-tml.
`tml_yaml_str = ts.metadata_tml_export_string(guid=x['id'], formattype='YAML', export_associated=False)
                tml_yaml_ordereddict = YAMLTML.load_string(tml_yaml_str)
                tml_obj = Worksheet(tml_yaml_ordereddict)
                modified_tml_string = YAMLTML.dump_tml_object(tml_obj)`

**Comment by venkataswetha1997** [comment]
I think I found out what the issue was. The thoughtspot-tml version. Now it's working perfectly fine. Thanks

**Comment by boonhapus** [comment]
That's great @venkataswetha1997 ! Thanks for confirming. Do also make sure you use the latest version of the [**REST API V1 wrapper**](https://github.com/thoughtspot/thoughtspot_rest_api_v1_python) as well.

This will give you the best experience of the links you listed above.
