### ISSUE TITLE
metadata/details API end is leaving out the last position from the json data

### ISSUE THREAD

**Issue by venkataswetha1997** [thoughtspot/thoughtspot_tml#12]
The metadata/details API end from tsrestapiv1 it's leaving the last position from the data which is nothing but the last column is dropped out while using this. For example if there are 81 positions in the json data from swagger for a particular guid_id, when this API end is used in code there are only 80 positions . Can you guys please check with this  @boonhapus @bryanthowell-ts @billdback-ts. Thanks
`details = ts.metadata_details(object_type='LOGICAL_TABLE', object_guids=[""])
print(details)`

**Comment by boonhapus** [comment]
This issue is not relevant to `thoughtspot_tml`. **[I've opened an issue](https://github.com/thoughtspot/thoughtspot_rest_api_v1_python/issues/11)** in the proper repo to track this one.
