### ISSUE TITLE
list_column_id getting added for parameters while parsing worksheet

### ISSUE THREAD

**Issue by cb1711** [thoughtspot/thoughtspot_tml#14]
Parsing worksheet tml with parameters using thoughtspot_tml and then dumping it to string adds list_column_id to the tml
Steps to repro:

1. Extract the given zip file
2. Run python test.py
3. The generated file new_worksheet.tml has list_column_id: "" also set

This causes issues while importing tml and the list values for the parameter are dropped
[Archive 2.zip](https://github.com/thoughtspot/thoughtspot_tml/files/12546864/Archive.2.zip)

**Comment by boonhapus** [comment]
Fixed as part of **[V2.0.10](https://github.com/thoughtspot/thoughtspot_tml/releases/tag/v2.0.10)**
