### ISSUE TITLE
Special characters don't get exported properly

### ISSUE THREAD

**Issue by MishaThoughtSpot** [thoughtspot/thoughtspot_tml#15]
When TML is exported, special characters are exported in their unicode format so instead of 'Perímetro Josu' (notice the accent on the i) it exports Per\xEDmetro Josu. This does not happen when TML is exported from the ThoughtSpot UI.

**Comment by boonhapus** [comment]
https://github.com/thoughtspot/thoughtspot_tml/blob/v2_main/src/thoughtspot_tml/_yaml.py#L90

We probably just need `allow_unicode=True`

Additional info: https://stackoverflow.com/a/29600111

**Comment by boonhapus** [comment]
This should be fixed as part of **[v2.0.8](https://github.com/thoughtspot/thoughtspot_tml/releases/tag/v2.0.8)**
