### ISSUE TITLE
TML Load Error: Id under tabs is not supported in Layout in tml_cls.loads

### ISSUE THREAD

**Issue by pankaj-lmg** [thoughtspot/thoughtspot_tml#20]
thoughstpot_tml Version: 1.7.0
Thoughtspot Version: 9.12.5.cl-220

When we create tabs in a liveboard, there is an ID being generated for each tab and the `tml_cls.loads` method is failing as it doesn't like this parameter. This used to work perfectly before as we had tabs to the liveboards but looks like there has been a change in Thoughtspot environment which is now putting the id also in tabs, but seems like the tml package is outdated and not expecting id. Since this ID is automatically created by ThoughtSpot TML, we are unable to push our changes.
We tried testing liveboards without Id in tabs and it is working fine so it's only the IDs created for tabs that is causing the issue.

**Use Case:**
We have a github action that fetches the liveboards tmls from thoughtspot, and push the tmls in github repo.

**Error Message:** 
```
PinboardLayoutTab.__init__() got an unexpected keyword argument 'id'
94
supplied data does not produce a valid TML (Liveboard) document
```

Id in the TML Looks like below:
![image](https://github.com/thoughtspot/thoughtspot_tml/assets/153048240/4f542f8d-0e5e-402e-8238-bce122dbce0a)

Python code:
![image](https://github.com/thoughtspot/thoughtspot_tml/assets/153048240/5a6602e3-fa76-437a-87a7-4866677b58a0)

Tried with different versions i.e. 1.5.7, 1.7.0 also, and still same issue.

**Comment by boonhapus** [comment]
@pankaj-lmg , can you **[upgrade to v2.0.16](https://github.com/thoughtspot/thoughtspot_tml/releases/tag/v2.0.16)** and try this one again ?

`pip install thoughtspot_tml --upgrade`

**Comment by boonhapus** [comment]
This should be fixed as part of the latest version.

https://github.com/thoughtspot/thoughtspot_tml/blob/9f6b2b875cfb4c9bb5454d84a289d439633a29f3/src/thoughtspot_tml/_scriptability.py#L839-L844

**Comment by pankaj-lmg** [comment]
Thanks @boonhapus . This is fixed now. You can close the issue
