### ISSUE TITLE
TML export for liveboards and answers have an issue with search query

### ISSUE THREAD

**Issue by venkataswetha1997** [thoughtspot/thoughtspot_tml#4]
I have used the code for exporting worksheets, tables, liveboards and answers. The worksheets and tables modified TML looks good. I have used YAMLTML.dump_tml_object(tml_object). The modified TML's for the liveboards and answers is missing open brace ([) and the first letter(A) from the search queries, the rest of the TML looks good. I have used these scripts to export. My ThoughtSpot version is 7.1.1 May I please know if there are any updates or something I'm missing with the search query.

1. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/examples/tml_and_sdlc/tml_yaml_intro.py
2. https://github.com/thoughtspot/thoughtspot_rest_api_v1_python/blob/main/src/thoughtspot_rest_api_v1/tsrestapiv1.py
3. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/endpoint_method_classes.py
4. https://github.com/thoughtspot/ts_rest_api_and_tml_tools/blob/main/thoughtspot.py
<img width="265" alt="Screen Shot 2022-10-18 at 2 25 23 PM" src="https://user-images.githubusercontent.com/57604273/196536660-06a799de-1369-4cef-8e7a-e995a973eb4c.png">

**Comment by venkataswetha1997** [comment]
I have attached both TML's in docx since I can't upload the .tml files directly. Thank's
[YAMLTML_Version.docx](https://github.com/thoughtspot/thoughtspot_tml/files/9832208/YAMLTML_Version.docx)
[UI_Version.docx](https://github.com/thoughtspot/thoughtspot_tml/files/9832209/UI_Version.docx)

**Comment by bryanthowell-ts** [comment]
Thank you for reporting this. I found the issue in the YAMLTML class and have corrected it in the 1.2.0 release that is now available on PyPi. Please let me know if you have any other issues with the exports

**Comment by venkataswetha1997** [comment]
Thanks the modified TML looks perfect now.
