### ISSUE TITLE
TML's for liveboards and answers exported through code have an issue with search query

### ISSUE THREAD

**Issue by venkataswetha1997** [thoughtspot/thoughtspot_tml#6]
Few of the liveboards and answers exported TML through script are have double quotes in the search query when compared against the manually exported TML don't have the double quotes. The manually exported TML have only single quotes. They are being replaced with double quotes when running the script. This issue is little glitchy because only few of the liveboards and answers are having this issue but not all. I'm able to import other liveboards and answers back to ThoughtSpot. I will be attaching both the versions of TML like manually exported and the one through script for both liveboard and answers. 
My current ThoughtSpot version is 7.1.1 
Can you please let me know if there are any updates or something. @boonhapus @bryanthowell-ts @billdback-ts 
[manual_answer.docx](https://github.com/thoughtspot/thoughtspot_tml/files/11019534/manual_answer.docx)
[script_answer.docx](https://github.com/thoughtspot/thoughtspot_tml/files/11019550/script_answer.docx)
[manual_liveboard.docx](https://github.com/thoughtspot/thoughtspot_tml/files/11019632/manual_liveboard.docx)
[script_liveboard.docx](https://github.com/thoughtspot/thoughtspot_tml/files/11019634/script_liveboard.docx)

**Comment by boonhapus** [comment]
Hi @venkataswetha1997 !

What version of the library are you using? We had some fixes that went in with 1.2.0 that helped with this area.

You can run this one to tell the version that's installed.

`python -c "import pkg_resources; print(pkg_resources.get_distribution('thoughtspot_tml').version)"`

**Comment by venkataswetha1997** [comment]
Previously, the issue was the first 2 characters were missing, later on I installed pip install install==1.2.0 and that issue was gone. When I ran the above command I see that I'm in 1.1.1

**Comment by boonhapus** [comment]
@venkataswetha1997 Let's bias towards using the latest released version. On V1.2.0 , what is the specific issue that you are seeing?

**Comment by venkataswetha1997** [comment]
When I **manually export** a TML for liveboard or answer the search query looks like : 
search_query: "[Estimated Onsite] [Assignment Count] [Received Date] [Received Date].monthly [ClaimXperience Policyholder Collaborated] [ClaimXperience Policyholder Collaborated].'policyholder collaborated'"
When I export that **through script** it looks like:
search_query: "[Estimated Onsite] [Assignment Count] [Received Date] [Received Date].monthly [ClaimXperience Policyholder Collaborated] [ClaimXperience Policyholder Collaborated].""policyholder collaborated"""

So whenever there is a single quote that's being replaced with double quotes. In the above example the policyholder collaborated is double quoted but that's not accepted by thoughtspot when I try to import it. It has to be in single quotes in order to import that back. Thanks

**Comment by venkataswetha1997** [comment]
I see that the code is merged, I'm currently using TSRESTAPIV1 in my script. May I please know what all I need to upgrade ?

**Comment by boonhapus** [comment]
You're fast @venkataswetha1997 ! ⚡ No changes to the public `YAMLTML` interface were made - only implementation of how we interact with yaml/tml files.

@bryanthowell-ts was able to merge and upload to pypi, you can simply run `pip install thoughtspot_tml --update` to take the latest.

Please let us know if the issues you are seeing are resolved.

**Comment by venkataswetha1997** [comment]
I have upgraded thoughtspot_tml and tested the liveboards and answers. They look good now and I'm able to import them back to ThoughtSpot. Thank you so much.

**Comment by boonhapus** [comment]
Great! Feel free to open another Issue if you find anything else interesting. 😄
